version: "3.9"

services:
  broker:
    build: .
    ports:
      - "18181:8080"
    volumes:
      - ./webhook-broker-dc.cfg:/webhook-broker.cfg
    command: ["./webhook-broker", "-migrate", "./migration/sqls/"]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql:mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webhook-broker
      MYSQL_USER: webhook_broker
      MYSQL_PASSWORD: zxc909zxc
    ports:
      - "44060:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 20s
      retries: 10
      start_period: 20s
