name: webhook-broker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.5'
    - name: Create dist
      run: mkdir ./dist/
    - name: Run Test & Build
      run: make dep-tools deps build test
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-app
        path: dist/webhook-broker-*.tar.bz2
